--Borrado de Vistas

DROP VIEW IF EXISTS GR15_Primer_trimestre_2020;
DROP VIEW IF EXISTS GR15_Eventos_por_distrito;
DROP VIEW IF EXISTS GR15_Categorias_Todas_Subcategorias;

--Borrado de Triggers y funciones

DROP TRIGGER IF EXISTS TR_GR15_Evento_Edicion_ControlFechas ON GR15_Evento_Edicion;
DROP TRIGGER IF EXISTS TR_GR15_Evento_ControlFechas ON GR15_Evento;

DROP TRIGGER IF EXISTS TR_GR15_Evento_IniciarEvento ON GR15_Evento;

DROP TRIGGER IF EXISTS TR_GR15_Evento_DistritoPatrocinio ON GR15_Evento;
DROP TRIGGER IF EXISTS TR_GR15_Patrocinios_DistritoPatrocinio ON GR15_Patrocinios;

DROP TRIGGER IF EXISTS TR_GR15_Evento_Edicion_LimiteAporte ON GR15_Evento_Edicion;
DROP TRIGGER IF EXISTS TR_GR15_Patrocinios_LimiteAporte ON GR15_Patrocinios;

DROP TRIGGER IF EXISTS TR_GR15_Subcategorias_MaxCategorias ON GR15_Subcategoria;

DROP FUNCTION IF EXISTS TRFN_GR15_MaxCategorias();
DROP FUNCTION IF EXISTS TRFN_GR15_LimiteAporte();
DROP FUNCTION IF EXISTS TRFN_GR15_DistritoPatrocinio();
DROP FUNCTION IF EXISTS TRFN_GR15_DistritoPatrocinio_2();
DROP FUNCTION IF EXISTS TRFN_GR15_IniciarEvento();
DROP FUNCTION IF EXISTS TRFN_GR15_ControlFechas();

-- Borrado de tablas en RESTRICT (PostgreSQL lo utiliza por defecto).
DROP TABLE IF EXISTS GR15_PATROCINIOS;
DROP TABLE IF EXISTS GR15_PATROCINANTE;

DROP TABLE IF EXISTS GR15_EVENTO_EDICION;
DROP TABLE IF EXISTS GR15_EVENTO;

DROP TABLE IF EXISTS GR15_USUARIO;

DROP TABLE IF EXISTS GR15_SUBCATEGORIA;
DROP TABLE IF EXISTS GR15_CATEGORIA;

DROP TABLE IF EXISTS GR15_DISTRITO;
DROP TABLE IF EXISTS GR15_PROVINCIA;
DROP TABLE IF EXISTS GR15_PAIS;

-- End of file.